### ISSUE TITLE
[BUG] re-used `img` are showing other images

### ISSUE THREAD

**Issue by joepadmiraal** [huafu/ember-img-manager#5]
First of all, thanks for this great addon.

I have configured a delay of one second and a batchSize of 1.
I have a dynamic route which contains a model with 3 image url's (imagelist/:list_id).
Those images are displayed with the img-wrap tag.
When I open the route for the first time the images first show the loading img and then show the correct image with one second delay each.

When I switch to another list_id 2 out of 3 img elements seem to be reused until they are loaded with the new image.
So those 2 img elements show the image from the previous route.
The loading class is set on all 3 img-wrap elements but only one of the img-wraps show the loading image.

I am using this environment:
ember-cli 0.2.0
ember 1.10.0
jQuery 1.11.2
ember-img-manager 0.0.12

Does this make any sense or should I create a gist to illustrate the issue?

**Comment by huafu** [comment]
Thanks for reporting, will try to have a look at it asap.

**Comment by huafu** [comment]
@joepadmiraal if you can test by running `npm install --save-dev huafu/ember-img-manager#5e72365` and then ember serve in your app, that would be a grateful help. It should fix it but I do not have time to test myself, very sorry.

Lemme know here if it's ok, and I'll then publish a new version.

**Comment by joepadmiraal** [comment]
@huafu Thanks for looking into this.
Unfortunately this does not seem to fix the issue.

The release method of img-clone-holder does not get executed.
releaseCloneHolder of img-wrap does get called, but `this.get('cloneHolder')` returns null.
If it helps I can setup a test repository which shows the problem.

**Comment by huafu** [comment]
Oh that would be great yeah! Thanks a lot for testing this.

**Comment by huafu** [comment]
If you yet did not setup the test repo, test 5fb962c. If it fixes it, then don't loose your time creating this test repo, else I guess I'll need it to debug.

**Comment by joepadmiraal** [comment]
I tested 5fb962c.
It now keeps all old images when changing to the new route.
After a while the new images appear, but no loading image is shown.

I created the test repo with the original ember-img-manager addon:
https://github.com/joepadmiraal/ember-img-manager-issue5

First click on Image-set 1 wait for the images to load and then click on Image-set 2.

**Comment by huafu** [comment]
thx, will drop an eye now

**Comment by joepadmiraal** [comment]
I did a small update to the test repo so you can run it with the current ember-cli version.
